-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 15, 2017 at 08:16 PM
-- Server version: 10.1.26-MariaDB
-- PHP Version: 7.1.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cstar`
--

-- --------------------------------------------------------

--
-- Table structure for table `ques_ans`
--

CREATE TABLE `ques_ans` (
  `id` int(5) NOT NULL,
  `ques` varchar(500) DEFAULT NULL,
  `op1` varchar(100) DEFAULT NULL,
  `op2` varchar(100) DEFAULT NULL,
  `op3` varchar(100) DEFAULT NULL,
  `op4` varchar(100) DEFAULT NULL,
  `ans` varchar(3) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `ques_ans`
--

INSERT INTO `ques_ans` (`id`, `ques`, `op1`, `op2`, `op3`, `op4`, `ans`) VALUES
(1, '#include<stdio.h><br>\r\n{<br>\r\nprintf(\"Hello World!\");<br>\r\n}<br>', 'Hello world!', 'Hello World', 'hello world', 'Hello World!', 'd'),
(2, 'Determine output:<br>\r\nvoid main()<br>\r\n{<br>\r\ninti=0, j=1, k=2, m;<br>\r\n      m = i++ || j++ || k++;<br>\r\nprintf(\"%d %d %d %d\", m, i, j, k);<br>\r\n}<br>\r\n', '1 1 2 3', '1 1 2 2', '0 1 2 2', '0 1 2 3', 'b'),
(3, 'Which of the following statements are correct about the program below?<br>\r\n#include<stdio.h><br>\r\n\r\nint main()<br>\r\n{<br>\r\n    int size, i;<br>\r\n    scanf(\"%d\", &size);<br>\r\n    int arr[size];<br>\r\n    for(i=1; i<=size; i++)<br>\r\n    {<br>\r\n        scanf(\"%d\", arr[i]);<br>\r\n        printf(\"%d\", arr', 'The code is erroneous since the subscript for array used in for  loop is in the range 1 to size.\r\n', 'The code is erroneous since the values of array are getting scanned through the loop.', 'The code is erroneous since the statement declaring array is invalid.', 'The code is correct and runs successfully', 'b'),
(4, 'In which numbering system can the binary number 1011011111000101 be  easily converted to?                                                                        ', 'decimal system', 'hexadecimal system', 'octal system', 'No need to convert', 'b'),
(5, 'What will be the output of the program ? <br>\r\n#include<stdio.h><br>\r\n\r\nint main()<br>\r\n{<br>\r\n    char *names[] = { \"Suresh\", \"Siva\", \"Sona\", \"Baiju\", \"Ritu\"};<br>\r\n    int i;<br>\r\n    char *t;<br>\r\n    t = names[3];<br>\r\n    names[3] = names[4];<br>\r\n    names[4] = t;<br>\r\n    for(i=0; i<=4; i++)<', 'Suresh, Siva, Sona, Baiju, Ritu', 'Suresh, Siva, Sona, Ritu, Baiju', 'Suresh, Siva, Baiju, Sona, Ritu', 'Suresh, Siva, Ritu, Sona, Baiju', 'b'),
(6, 'What will be the output of the program ?<br>\r\n\r\n#include<stdio.h><br>\r\n\r\nvoid fun(void *p);<br>\r\nint i;<br>\r\n\r\nint main()<br>\r\n{<br>\r\n    void *vptr;<br>\r\n    vptr = &i;<br>\r\n    fun(vptr);<br>\r\n    return 0;<br>\r\n}<br>\r\nvoid fun(void *p)<br>\r\n{<br>\r\n    int **q;<br>\r\n    q = (int**)&p;<br>\r\n    pri', 'Error: cannot convert from void* to int** ', 'garbage value', '0', 'no output', 'c'),
(7, 'What is output?<br>\r\n# include <stdio.h><br>\r\n \r\nvoid print(int arr[])<br>\r\n{<br>\r\n   int n = sizeof(arr)/sizeof(arr[0]);<br>\r\n   int i;<br>\r\n   for (i = 0; i < n; i++)<br>\r\n      printf(\"%d \", arr[i]);<br>\r\n}<br>\r\n<br> \r\nint main()<br>\r\n{<br>\r\n   int arr[] = {1, 2, 3, 4, 5, 6, 7, 8};<br>\r\n   print(arr);<br>\r\n   return 0;<br>\r\n}', '1, 2, 3, 4, 5, 6, 7, 8', 'Compiler Error', '1', 'Run Time Error', '1'),
(8, 'What will be the output of the program?<br>\r\n#include<stdio.h><br>\r\n#include<string.h><br>\r\n\r\nint main()<br>\r\n{<br>\r\n    char *s;<br>\r\n    char *fun();<br>\r\n    s = fun();<br>\r\n    printf(\"%s\n\", s);<br>\r\n    return 0;<br>\r\n}<br>\r\nchar *fun()<br>\r\n{<br>\r\n    char buffer[30];<br>\r\n    strcpy(buffer, \"', '0xffff', 'garbage value', '0xffee', 'error', 'b'),
(9, 'How will you free the memory allocated by the following program?<br>\r\n#include<stdio.h><br>\r\n#include<stdlib.h><br>\r\n#define MAXROW 3<br>\r\n#define MAXCOL 4<br>\r\n\r\nint main()<br>\r\n{<br>\r\n    int **p, i, j;<br>\r\n    p = (int **) malloc(MAXROW * sizeof(int*));<br>\r\n    return 0;<br>\r\n}<br>\r\n', 'memfree(int p);', 'dealloc(p);', 'malloc(p, 0);', 'free(p);      ', 'd'),
(10, 'What will be output of following c code?<br>\r\n#include<stdio.h><br>\r\nextern int x;<br>\r\nint main()<br>\r\n{<br>\r\n    do{<br>\r\n        do{<br>\r\n             printf(\"%o\",x);<br>\r\n         }<br>\r\n         while(!-2);<br>\r\n    }<br>\r\n    while(0);<br>\r\n    return 0;<br>\r\n}<br>\r\nint x=8;<br>\r\n', '2', '8', '10', 'error', 'c'),
(11, 'what will be output of following c code? <br>\r\n#include<stdio.h><br>\r\nchar _x_(int,...);<br>\r\nint main()<br>\r\n{<br>\r\n    char (*p)(int,...)=&_x_;<br>\r\n    for(;(*p)(0,1,2,3,4); )<br>\r\n         printf(\"%d\",!+2);<br>\r\n    return 0;<br>\r\n}<br>\r\nchar _x_(int a,...)<br>\r\n{<br>\r\n    static i=-1;<br>\r\n    ', '0 1 2 3 4', 'garbage value', '4 3 2 1 0', '0', 'd'),
(12, 'What will be the output of the program ? <br>\r\n#include<stdio.h> <br>\r\nint main() <br>\r\n{    <br>\r\nint a[5] = {5, 1, 15, 20, 25};  <br>\r\ninti, j, m;  <br>\r\ni = ++a[1];   <br>\r\nj = a[1]++;   <br>\r\nm = a[i++];  <br>\r\nprintf(\"%d, %d, %d\", i, j, m);  <br>\r\nreturn 0;   <br>\r\n}   <br>\r\n\r\n', '\r\n3,2,15', '6,2,15', '4,3,15', '3,3,15', 'a'),
(13, 'Which of the following statement is True? <br>\r\n\r\n', 'User has to explicitly define the numeric value of enumerations\r\n', 'User has a control over the size of enumeration variables.\r\n', 'Enumeration can have an effect local to the block, if desired', 'Enumerations have a global effect throughout the file.\r\n', 'c'),
(14, '#include <stdio.h><br> \r\nint main() <br>\r\n{ <br>\r\n  int a = 10, b = 20, c = 30; <br>\r\n  if (c > b > a)<br> \r\n    printf(\"TRUE\"); <br>\r\n  else<br>\r\n    printf(\"FALSE\"); <br>\r\n  return 0; <br>\r\n}', 'True', 'False', 'Compiler Error', 'Output is Compiler dependent', 'b'),
(15, 'If #include is used with file name in angular brackets? <br>\r\n', 'The file is searched for in the standard compiler include paths.\r\n', 'The search path is expanded to include the current source directory', ' Both a & b', 'None of the mentioned', 'c'),
(16, 'What would happen if you create a file stdio.h and use #include â€œstdio.hâ€ ?<br>\r\n \r\n', 'The predefined library file will be selected', 'The user-defined library file will be selected', 'Both the files will be included', 'The compiler wonâ€™t accept the program', 'b'),
(17, 'Consider on following declaration in c: <br>\r\n\r\n(i)shortconst register i=10; <br>\r\n(ii)static volatile constinti=10;  <br>\r\n(iii)unsigned auto long register i=10;  <br>\r\n(iv)signed extern float i=10.0;  <br>\r\n\r\nChoose correct one: <br>', 'only (iv)is correct', 'only (ii) and (iv) is correct', 'only (i) and (ii) is correct', 'all are correct declaration', 'c'),
(18, 'What is (void*)0?<br>\r\n\r\n', 'Representation of NULL pointer', 'Representation of void pointer', 'Error', 'None of above', 'a'),
(19, 'What will be the output when you will execute following code?  <br>\r\n\r\n#include<stdio.h>  <br>\r\nenum A  <br>\r\n{    <br>\r\nx,y=5,  <br>\r\nenum B  <br>\r\n{      <br>\r\np=10,q  <br>\r\n}  <br>\r\nvarp;  <br>\r\n}  <br>\r\nvarx;  <br>\r\nint main()  <br>\r\n{    <br>\r\nprintf(\"%d %d\",x,varp.q);  <br>\r\nreturn 0;   <br>\r\n', '0 11', 'compilation error', 'runtime and compilation errors', '0 10', 'b'),
(20, 'In which header file is the NULL macro defined?<br>\r\n\r\n', 'stdio.h', 'stddef.h', 'stdio.h and stddef.h', 'math.h', 'c'),
(21, '#include<stdio.h>  <br>\r\nint main()   <br>\r\n{    <br>\r\nint a=-5;   <br>\r\nunsigned int b=-5u; <br>\r\nif(a==b) <br>\r\nprintf(\"Avatar\");  <br>\r\nelse   <br>\r\nprintf(\"Alien\");  <br>\r\nreturn 0;   <br>\r\n}  <br>\r\n\r\nChoose all that apply:   <br>\r\n', 'Avatar', 'Alien', 'runtime error', 'error: illegal assignment', 'a'),
(22, 'Which of the following statements correct about the below code?<br>\r\nmaruti.engine.bolts=25;<br>\r\n            \r\n', 'Structure bolts is nested within structure engine.\r\n', ' Structure engine is nested within structure maruti.', 'Structure maruti is nested within structure engine.', 'Structure maruti is nested within structure bolts.\r\n', 'b'),
(23, '#include<stdio.h>  <br>\r\nint main()  <br>\r\n{   <br>\r\nprintf(\"IndiaBIX\");  <br>\r\n    main();   <br>\r\n    return 0;   <br>\r\n}   <br>\r\n', 'infinite times', '32767 times', '65535 times', 'till stack overflows', 'd'),
(24, 'What is the similarity between a structure, union and enumeration?<br>\r\n	\r\n', 'All of them let you define new values', 'All of them let you define new data types', 'All of them let you define new pointers', 'All of them let you define new structure\r\n', 'b'),
(25, 'What is the output of this C code?<br>\r\n        #include<stdio.h><br>\r\n	int main()<br>\r\n	{<br>\r\n	signed int chr;<br>\r\n	chr=128;<br>\r\n	printf(â€œ%d\nâ€,chr);<br>\r\n	return 0;<br>\r\n	}<br>\r\n	\r\n', '128\r\n', '-128', 'Depends on the compiler', 'None of the above', 'b'),
(26, 'What will be the output of the program?   <br>\r\n\r\n#include<stdio.h>   <br>\r\nvoid fun(int);   <br>\r\ntypedef int (*pf) (int, int);   <br> \r\nint proc(pf, int, int);   <br>\r\n\r\nint main()  <br>\r\n{   <br>\r\n    int a=3;  <br>\r\n    fun(a);  <br>\r\n    return 0;  <br>\r\n}   <br>\r\nvoid fun(int n)   <br>\r\n{   <b', '0, 2, 1, 0,', '1, 1, 2, 0,', '0, 1, 0, 2,', '0, 1, 2, 0,', 'd'),
(27, 'What does the following command line signify?  <br>\r\n               \r\n\r\n            prog1|prog2   <br>\r\n ', 'It runs prog1 first, prog2 second', 'It runs prog2 first, prog1 second', 'It runs both the programs, pipes output of prog1 to input of prog2', 'It runs both the programs, pipes output of prog2 to input of prog1', 'c'),
(28, 'What is the output of this C code?<br>\r\n#include &lt;stdio.h&gt;<br>\r\nint main()<br>\r\n{<br>\r\nint a = 2;<br>\r\nint b = 0;<br>\r\nint y = (b == 0) ? a :(a &gt; b) ? (b = 1): a;<br>\r\nprintf(&quot;%d\n&quot;, y);<br>\r\n}<br>\r\n', 'Compile time error', '1', '2', 'Undefined behavior', 'c'),
(29, 'What is the output of this C code?<br>\r\n#include &lt;stdio.h&gt;\r\n<br>enum birds {SPARROW, PEACOCK, PARROT};<br>\r\nenum animals {TIGER = 8, LION, RABBIT, ZEBRA};<br>\r\nint main()<br>\r\n{<br>\r\nenum birds m = TIGER;<br>\r\nint k;<br>\r\nk = m;<br>\r\nprintf(&quot;%d\n&quot;, k);<br>\r\nreturn 0;<br>\r\n}<br>', '0', 'Compile time error', '1', '8', 'd'),
(30, 'Does logical operators in C language are evaluated with short\r\ncircuit?<br>', 'True', 'False', 'Depends on the compiler', 'Depends on the standard', 'a'),
(31, 'Predict the output<br>\r\n \r\n#include <stdio.h><br>\r\n \r\nint main()<br>\r\n{<br>\r\n   float c = 5.0;<br>\r\n   printf (\"Temperature in Fahrenheit is %.2f\", (9/5)*c + 32);<br>\r\n   return 0;<br>\r\n}<br>\r\n\r\n', 'Temperature in fahrenheit is 37.00', 'Temperature in fahrenheit is 41.00', 'Temperature in fahrenheit is 00.00', 'compile error', 'a'),
(32, 'There is a error in the below program. Which statement will you\r\nadd to remove it?<br>\r\n#include&lt;stdio.h&gt;<br>\r\nint main()<br>\r\n{<br>\r\nint a;<br>\r\na = f(10, 3.14);<br>\r\nprintf(&quot;%d\n&quot;, a);<br>\r\nreturn 0;<br>\r\n}<br>\r\nfloat f(int aa, float bb)<br>\r\n{<br>\r\nreturn ((float)aa + bb);<br>\r\n}<b', 'Add prototype: float f(aa, bb)', 'Add prototype: float f(int, float)', 'Add prototype: float f(float, int)', 'Add prototype: float f(bb, aa)', 'b'),
(33, 'Output of following program?<br>\r\n#include<stdio.h><br> \r\n   \r\nint main() <br>\r\n{ <br>\r\n  int a[] = {1, 2, 3, 4, 5, 6};<br>\r\n  int *ptr = (int*)(&a+1); <br>\r\n  printf(\"%d \", *(ptr-1) ); <br>\r\n  return 0; <br>\r\n}', '1', '2', '6', 'Run time error', 'c'),
(34, 'The output of the following program is:<br>\r\n#define f(g,g2) g##g2<br>\r\nvoid main()<br>\r\n{<br>\r\nint var12=100;<br>\r\nprintf(&quot;%d&quot;, f(var,12));<br>\r\n}<br>', 'Syntax error', 'Runtime error', 'g##g2', '100', 'd'),
(35, 'What is the output of this C code?<br>\r\n  #include <stdio.h><br>\r\n    int main()<br>\r\n    {<br>\r\n        int i = 10;<br>\r\n        void *p = &i;<br>\r\n        printf(\"%f\r\n\", *(float*)p);<br>\r\n        return 0;<br>\r\n    }<br>\r\n\r\n', 'Compile time error', 'Undefined behaviour', '10', '0.000000', 'd'),
(36, '#include <stdio.h><br>\r\n \r\nint main()<br>\r\n{<br>\r\n    int arr[5];<br>\r\n     \r\n    // Assume that base address of arr is 2000 and size of integer<br>\r\n        // is 32 bit<br>\r\n    arr++;<br>\r\n    printf(\"%u\", arr);<br>\r\n     \r\n    return 0;<br>\r\n}<br>', '2002', '2004', '2020', 'lvalue required', 'd'),
(37, '#include <stdio.h><br>\r\n    void foo(float *);<br>\r\n    int main()<br>\r\n    {<br>\r\n        int i = 10, *p = &i;<br>\r\n        foo(&i);<br>\r\n    }<br>\r\n    void foo(float *p)<br>\r\n    {<br>\r\n        printf(\"%f\n\", *p);<br>\r\n    }<br>\r\n\r\nThe output is:<br>', '10.000000', ' 0.000000', 'Compile time error', 'Undefined behaviour', 'b'),
(38, 'What will be the output of the program assuming that the array begins at the location 1002 and size of an integer is 4 bytes?<br>\r\n\r\n#include<stdio.h><br>\r\n\r\nint main()<br>\r\n{<br>\r\n    int a[3][4] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };<br>\r\n    printf(\"%u, %u, %u\\n\", a[0]+1, *(a[0]+1), *(*(a+0)+1));<br>\r\n    return 0;<br>\r\n}<br>', '448, 4, 4', '520, 2, 2', '1006, 2, 2', 'error', 'c'),
(39, 'What is the output of this C code?<br>\r\n#include <stdio.h><br>\r\n    int main()<br>\r\n    {<br>\r\n        int i = 10;<br>\r\n        int *p = &i;<br>\r\n        foo(&p);<br>\r\n        printf(\"%d \", *p);<br>\r\n        printf(\"%d \", *p);<br>\r\n    }<br>\r\n    void foo(int **const p)<br>\r\n    {<br>\r\n        int j', '11 11 11', '11 11 Undefined-value', 'Compile time error', 'Segmentation fault/code-crash', 'b'),
(40, 'In the below statement, ptr1 and ptr2 are uninitialized pointers to int i.e. they are pointing to some random address that may or may not be valid address.<br>\r\nint* ptr1, ptr2;', 'TRUE', 'FALSE', 'Cannot be determined', 'None of the Above', 'b'),
(41, 'What is the output of this C code?   <br>\r\n\r\n#include <stdio.h>   <br>\r\nint main()    <br>\r\n    {   <br>\r\n        if (7 & 8)  <br>\r\nprintf(\"Honesty\");   <br>\r\n            if ((~7 & 0x000f) == 8)   <br>\r\nprintf(\"is the best policy\n\");    <br>\r\n    }   <br>\r\n', 'Honesty is the best policy', 'Honesty', 'is the best policy', 'no output', 'c'),
(42, ' Which header statement is missing in the given below program to get the desired output?\r\n<br>\r\n#include<stdio.h><br>\r\n#include<math.h><br>\r\n\r\nint main ()<br>\r\n{<br>\r\n   double x = 1234321;\r\n<br>\r\n   double result = sqrt(x);\r\n<br>\r\nprintf(\"The square root of %.2lf is %.2lf\n\", x, result);\r\n   <br>ret', '#include defs.h \r\n\r\n', '#include math.h ', '#include stdlib.h', 'Above program is absolutely correct to give desired result', 'b'),
(43, 'Which of the following pre-defined functions returns a pointer to the last  <br>\r\noccurrence of a character  in a string?   <br>\r\nOptions: <br>\r\n', 'strchr(s,c);', 'strrchr(s,c);', 'strlchr(s,c);', 'strfchr(s,c);', 'b'),
(44, 'Which library function can convert an unsigned long to a string?  <br>', 'itoa()', 'unsigned long canâ€™t be converted to a string', 'system()', 'ultoa()', 'd'),
(45, 'What will be the output of the following program?  <br>\r\n#include<stdio.h>   <br>\r\nint main()   <br>   \r\n{    <br>\r\n	float f=0x21E02F;   <br>\r\n	char *str=\"%.2f;   <br>\r\n	printf(str,f);   <br>\r\n	return 0;    <br>\r\n}    <br>\r\n', '0x21E02.00', '222079.00', '21*10^2', '21*10^2', 'b'),
(46, 'Which of the following statements about stdout and stderr are true? <br>\r\n', 'same', 'Both connected to screen always. ', 'Both connected to screen by default. ', 'stdout is line buffered but stderr is unbuffered.', 'c'),
(47, 'In the following program add a statement in the function fact() such that the factorial gets stored in j.<br>\r\n#include<stdio.h><br>\r\nvoid fact(int*);<br>\r\n\r\nint main()<br>\r\n{<br>\r\n    int i=5;<br>\r\n    fact(&i);<br>\r\n    printf(\"%d\n\", i);<br>\r\n    return 0;<br>\r\n}<br>\r\nvoid fact(int *j)<br>\r\n{<br>\r', 'j=s;', '*j=s;', '*j=&s;', '&j=s;', 'b'),
(48, 'What is the output of this C code?  <br>\r\n#include <stdio.h>  <br>\r\n    union <br>\r\n    {   <br>\r\n        int x;   <br>\r\n        char y;  <br>\r\n    }p; <br>\r\n    int main()   <br>\r\n    {   <br>\r\n        p.y = 60;   <br>\r\n        printf(\"%d\n\", sizeof(p));   <br>\r\n     }   <br>', 'Compile time error', 'sizeof(int) + sizeof(char)', 'Depends on the compiler', 'sizeof(char)', 'c'),
(49, 'Comment on the output of this C code?<br>\r\n#include <stdio.h><br>\r\nstruct temp<br>\r\n{<br>\r\nint a;<br>\r\n} s;<br>\r\nvoid change(struct temp);<br>\r\n    main()<br>\r\n{<br>\r\ns.a=10;<br>\r\n        change(s);<br>\r\nprintf(\"%d\n\",s.a);<br>\r\n}<br>\r\nvoid change(struct temp s)<br>\r\n{<br>\r\ns.a=1;<br>\r\n}<br>\r\n', 'Output will be 1', 'Output will be 10', 'Output varies with machine', 'Compile time error', 'b'),
(50, 'For the following declaration of structure, which of the following will stop the loop at the last node of a linked list?<br>\r\nstruct node<br>\r\n{<br>\r\nstruct node *next;<br>\r\n};<br>\r\n', 'while (p != NULL)\r\n{\r\n        p = p->next;\r\n    }\r\n', 'while (p->next != NULL)\r\n    {\r\n        p = p->next;\r\n    }\r\n', 'while (1)\r\n    {\r\n        p = p->next;\r\n        if (p == NULL)\r\n            break;\r\n    }\r\n', 'All of the mentioned', 'b'),
(51, 'What will be output if you will compile and execute the following c code?<br>\r\n<br>\r\nstruct marks{<br>\r\nint p:3;<br>\r\nint c:3;<br>\r\nint m:2;<br>\r\n};<br>\r\nvoid main(){<br>\r\nstruct marks s={2,-6,5};<br>\r\nprintf(\"%d %d %d\",s.p,s.c,s.m); <br>\r\n}<br>\r\n', '2 -6 5', '2 -6 1', '2 2 1', 'Compiler error', 'c'),
(52, 'What is the output of this C code?<br>\r\n    #include <stdio.h><br>\r\n    void main()<br>\r\n    {<br>\r\nint x = 4;<br>\r\nint *p = &x;<br>\r\nint *k = p++;<br>\r\nint r = p - k;<br>\r\nprintf(\"%d\", r);<br>\r\n    }<br>\r\n', '4', '8', '1', 'Run time error', 'c'),
(53, 'Consider the following C program segment:<br>\r\nchar p[20]; <br>\r\nchar *s = \"string\";<br> \r\nint length = strlen(s);<br> \r\nint i; <br>\r\nfor (i = 0; i < length; i++) <br>\r\n    p[i] = s[length — i]; <br>\r\nprintf(\"%s\", p);<br>\r\nThe output of the program is?<br>', 'gnirts', 'gnirt', 'string', 'no output is printed', 'b'),
(54, 'O/P IS:<br>\r\n Main() <br>                                                                                            \r\n  { <br>\r\ninti=-1,j=-1,k=0,l=2,m; <br>\r\n     m=i++&&j++&&k++||l++; <br>\r\nprintf(â€œ%d%d%d%d%dâ€,I,j,k,l,m); <br>\r\n}\r\n<br>', '01310', '0013 1 ', '11300', '00013', 'b'),
(55, 'What will be output if you will compile and execute the following c code?<br>\r\n\r\nvoid main(){\r\nint huge*p=(int huge*)0XC0563331;\r\nint huge*q=(int huge*)0xC2551341;\r\n   *p=200;\r\nprintf(\"%d\",*q);\r\n}\r\n\r\nA)\r\nB) \r\nC) \r\nD) 200\r\nE) Compiler error\r\n\r\n', ' 0', 'Garbage value', 'null', '200', 'd'),
(56, 'Assume that size of an integer is 32 bit. What is the output of following program?<br>\r\n#include<stdio.h><br>\r\nstruct st<br>\r\n{<br>\r\n    int x;<br>\r\n    static int y;<br>\r\n};<br>\r\n <br>\r\nint main()<br>\r\n{<br>\r\n    printf(\"%d\", sizeof(struct st));<br>\r\n    return 0;<br>\r\n}', '4', '8', 'Compiler Error', 'Runtime Error', 'c'),
(57, 'What is the difference between the following 2 codes?<br>\r\n    #include <stdio.h> //Program 1<br>\r\nint main()<br>\r\n    {<br>\r\nint d, a = 1, b = 2;<br>\r\n        d =  a++ + ++b;<br>\r\nprintf(\"%d %d %d\", d, a, b);<br>\r\n    }<br>\r\n    #include <stdio.h> //Program 2<br>\r\nint main()<br>\r\n    {<br>\r\nint d, ', 'No difference as space doesn\'t make any difference, values of a, b, d are same in both the case', 'Space does make a difference, values of a, b, d are different', 'Program 1 has syntax error, program 2 is not', 'Program 2 has syntax error, program 1 is not', 'd'),
(58, 'Which of the following are incorrect syntax for pointer to structure?<br>\r\n(Assuming struct temp{int b;}*my_struct;)<br>\r\n', '*my_struct.b = 10;', '(*my_struct).b = 10;', ' my_struct->b = 10;', 'Both (a) and (b)', 'a'),
(59, 'What will be output if you will compile and execute the following c code?<br>\r\n\r\nvoid main(){\r\ninti;\r\ndouble a=5.2;\r\nchar *ptr;\r\nptr=(char *)&a;\r\nfor(i=0;i<=7;i++)\r\nprintf(\"%d \",*ptr++);\r\n}\r\n\r\n\r\n\r\n', '-51 -52 -52 -52 -52 -52 20 64\r\n', '51 52 52 52 52 52 20 64 ', 'Eight garbage values.', 'Compiler error', 'a'),
(60, '#include \"stdio.h\"<br>\r\n\r\nint main()<br>\r\n{<br>\r\n    int i = (1, 2, 3);<br>\r\n    \r\n    printf(\"%d\", i);<br>\r\n    \r\n    return 0;<br>\r\n}', '1', '2', '3', 'Compiler error', 'c'),
(61, 'This program will allocate the memory of ___ bytes for pointer â€œptrâ€.<br>\r\n#include<stdio.h><br>\r\n#include<stdlib.h><br>\r\n \r\nint main()<br>\r\n{<br>\r\nint*ptr;<br>\r\nptr=(int*)malloc(sizeof(int)*4);<br>\r\nptr=realloc(ptr,sizeof(int)*2);<br>\r\nreturn0;<br>\r\n}<br>\r\n', '2', '4', '8', 'none of the mentioned', 'c'),
(62, 'What will be output if you will compile and execute the following c code?<br>\r\n\r\nvoid main(){<br>\r\nint huge*p=(int huge*)0XC0563331;<br>\r\nint huge*q=(int huge*)0xC2551341;<br>\r\n   *p=200;<br>\r\nprintf(\"%d\",*q);<br>\r\n}<br>\r\n\r\n', ' 0', 'Garbage value', 'null', '200', 'd'),
(63, '#include <stdio.h><br>\r\n\r\nint main()<br>\r\n{<br>\r\n    int i;<br>\r\n    \r\n    i = 1, 2, 3;<br>\r\n    printf(\"%d\", i);<br>\r\n    \r\n    return 0;<br>\r\n}', ' 1', 'Garbage value', '2', 'Compile Time Error', 'a'),
(64, 'What is the output of this program?<br>\r\n#include<stdio.h><br>\r\n#include<stdlib.h>\r\n <br>\r\nint main()<br>\r\n{<br>\r\nint*ptr;<br>\r\n*ptr=10;S<br>\r\n*ptr=20;<br>\r\nprintf(\"%d\n\",*ptr);<br>\r\nreturn0;<br>\r\n}<br>\r\n', '10', '20', 'segmentationfault', 'none of the mentioned', 'c'),
(65, '#include <stdio.h><br>\r\nint main()<br>\r\n{<br>\r\n    int i = 3;<br>\r\n    printf(\"%d\", (++i)++);<br>\r\n    return 0;<br>\r\n}', '3', '4', '5', 'Compiletime error', 'd'),
(66, 'What is the output of this C code?<br>\r\n	    #include <stdio.h><br>\r\n	struct p<br>\r\n	    {<br>\r\n	int x;<br>\r\n	char y;<br>\r\n	    };<br>\r\n	typedefstruct p* q*;<br>\r\n	int main()<br>\r\n	    {<br>\r\n	struct p p1[] = {1, 92, 3, 94, 5, 96};<br>\r\n	        q ptr1 = p1;<br>\r\n	printf(\"%d\n\", ptr1->x);<br>\r\n	    }', 'Compile time error', '1', 'Undefined behaviour', 'Segmentation fault', 'a'),
(67, 'What is printed by the following C program?<br>\r\n#include <stdio.h><br>\r\nint f(int x, int *py, int **ppz)<br>\r\n{<br>\r\nint y, z;<br>\r\n  **ppz += 1;<br>\r\nz= **ppz;<br>\r\n  *py += 2;<br>\r\n   y = *py;<br>\r\n   x += 3;<br>\r\nreturn x + y + z;<br>\r\n}<br>\r\n\r\nvoid main()<br>\r\n{<br>\r\nint c, *b, **a;<br>\r\n   c =4; b = &c; a = &b;<br>\r\n    printf(\"%d\", f(c, b, a));<br>\r\n    	<br>\r\n}', '18', '19', '21', '22', 'b'),
(68, 'Predict output of following program<br>\r\nint main()<br>\r\n{<br>\r\n    int i;<br>\r\n    int arr[5] = {1};<br>\r\n    for (i = 0; i < 5; i++)<br>\r\n        printf(\"%d \", arr[i]);<br>\r\n    return 0;<br>\r\n}', '1 followed by four garbage values', '1 0 0 0 0', '1 1 1 1 1', '0 0 0 0 0', 'b'),
(69, 'Assume sizeof an integer and a pointer is 4 byte. Output?<br>\r\n#include <stdio.h><br>\r\n#define R 10<br>\r\n#define C 20<br>\r\n\r\nint main()<br>\r\n{<br>\r\nint (*p)[R][C];<br>\r\nprintf(\"%d\",  sizeof(*p));<br>\r\ngetchar();<br>\r\nreturn 0;<br>\r\n}<br>\r\n\r\n', '200', '4', '800', '80', 'c'),
(70, 'For the following function call which option is not possible?\r\n<br>\r\nfunc(&s.a); //where s is a variable of type struct and a is the member of the struct.\r\n\r\n', 'Compiler can access entire structure from the function.', 'Individual members address can be displayed in structure.', 'Individual member can be passed by reference in a function.', 'Both (B) and (C).', 'a'),
(71, 'Data type qualifiers can be classified into?', '4', '5', '2', '8', 'c'),
(72, '#include \"stdio.h\"<br>\r\nint main() <br>\r\n{ <br>\r\n  int x, y = 5, z = 5;<br> \r\n  x = y == z;<br> \r\n  printf(\"%d\", x);<br> \r\n  \r\n  getchar(); <br>\r\n  return 0; <br>\r\n}', '0', '1', '5', 'Compiler Error', 'b'),
(73, 'Output of following program<br>\r\n#include <stdio.h><br>\r\nint fun(int arr[]) <br>\r\n{<br>\r\n   arr = arr+1;<br>\r\n   printf(\"%d \", arr[0]);<br>\r\n}<br>\r\nint main(void)<br>\r\n{<br>\r\n   int arr[2] = {10, 20};<br>\r\n   fun(arr);<br>\r\n   printf(\"%d\", arr[0]);<br>\r\n   return 0;<br>\r\n}<br>\r\n\r\n\r\n', 'Compiler Error', '20 10', '20 20', '10 10', 'b'),
(74, 'Preprocessor directive\r\n<br>#ubdef can be used only on a macro that has been \r\n<br>#define earlier', 'true', 'false', 'cannot determine', 'irrelavent', 'a'),
(75, 'What is the output of this C code?<br>\r\n\r\n    #include <stdio.h><br>\r\n    union p<br>\r\n    {<br>\r\n        int x;<br>\r\n        char y;<br>\r\n    }k = {1, 97};<br>\r\n    int main()<br>\r\n    {<br>\r\n        printf(\"%d\n\", k.y);<br>\r\n    }<br>\r\n', 'Compile time error', ' 97', 'a', '1', 'd'),
(76, 'Which of the following statements are true?\r\n P. Pointer to Array\r\n Q. Multi-dimensional array\r\n\r\n\r\n\r\n', 'P are static, Q are static', ' P are static, Q are dynamic\r\n', 'P are dynamic, Q are dynamic', 'P are dynamic and Q are static', 'd'),
(77, 'Which of the following header file can be used to define the NULL macro?\r\n\r\n<br>', 'stdio.h, locale.h, stddef.h, stdlib.h, string.h,', 'stddef.h, locale.h, math.h, stdlib.h, string.h,', 'time.h, wchar.h, math.h, locale.h,', 'math.h', 'a'),
(78, '#include are _______ files and #include \"somefile.h\" ________ files.', 'Library, Library', 'Library, user-created header', 'User-created header, library', 'They can include all types of file', 'd'),
(79, 'Predict the output of below program:<br>\r\n#include <stdio.h><br>\r\nint main()<br>\r\n{<br>\r\n    int arr[5];<br>\r\n    // Assume base address of arr is 2000 and size of integer is 32 bit<br>\r\n    printf(\"%u %u\", arr + 1, &arr + 1);<br>\r\n \r\n    return 0;<br>\r\n}<br>\r\n', '2004 2020', '2004 2004', '2004 Garbage value', 'The program fails to compile because Address-of operator cannot be used with array name', 'a'),
(80, 'What will be the output of the following program?<br>\r\n#include<stdio.h><br>\r\n#define prod(a,b)  a*b<br>\r\nvoid main()<br>\r\n{<br>\r\nint x=3,y=4;<br>\r\nprintf(\"%d\", prod(x+2,y-1));<br>\r\n}<br>\r\n', '12', '10', '11', 'None of the above', 'c'),
(81, 'What will be the output of the following program?<br>\r\n\r\n#include<stdio.h><br>\r\n#include<string.h><br>\r\nint main()<br>\r\n{<br>\r\nstatic char s[]=â€helloâ€;<br>\r\nprintf(â€œ%dâ€,*(s+strlen(s)));<br>\r\nreturn 0;<br>	\r\n}<br>\r\n\r\n', '8', '0', '16', 'Error', 'b'),
(82, 'Which command is used to copy all files having the string chap and any two characters after that to the progs directory?                                                                     ', 'cp chap?? progs', 'cp chap* progs', 'cpchap[12] /progs/*.*', 'cp chap?? /progs/*', 'a'),
(83, 'Suppose that in a C program snippet, followings statements are used.\r\n<br>\r\ni) sizeof(int);<br>\r\nii) sizeof(int*);<br>\r\niii) sizeof(int**);<br>\r\n\r\nAssuming size of pointer is 4 bytes and size of int is also 4 bytes, pick the most correct answer from the given options.<br>', 'Only i) would compile successfully and it would return size as 4.', 'i), ii) and iii) would compile successfully and size of each would be same i.e. 4', 'i), ii) and iii) would compile successfully but the size of each would be different and would be dec', 'ii) and iii) would result in compile error but i) would compile and result in size as 4', 'b'),
(84, 'What will be output if you will compile and execute the following c code?<br>\r\n\r\nvoid main(){<br>\r\nint i=10;<br>\r\nstatic int x=i;<br>\r\nif(x==i)<br>\r\nprintf(\"Equal\");<br>\r\nelse if(x>i)<br>\r\nprintf(\"Greater than\");<br>\r\nelse<br>\r\nprintf(\"Less than\");<br>\r\n}<br>\r\n\r\n', ' Equal', 'Greater than', 'Less than', 'Compiler error', 'd'),
(85, 'What is the output of following program?<br>\r\n#include <stdio.h><br>\r\n \r\nint main()<br>\r\n{<br>\r\n   int a = 1;<br>\r\n   int b = 1;<br>\r\n   int c = a || --b;<br>\r\n   int d = a-- && --b;<br>\r\n   printf(\"a = %d, b = %d, c = %d, d = %d\", a, b, c, d);<br>\r\n   return 0;<br>\r\n}', 'a = 0, b = 1, c = 1, d = 0', 'a = 0, b = 0, c = 1, d = 0 ', 'a = 1, b = 1, c = 1, d = 1', 'a = 0, b = 0, c = 0, d = 0', 'b'),
(86, 'What is the output of the following C code? Assume that the address of x is 2000 (in decimal) and an integer requires four bytes of memory.<br>\r\n#include <stdio.h><br>\r\nint main()<br>\r\n{<br>\r\n   unsigned int x[4][3] = {{1, 2, 3}, {4, 5, 6},\r\n                           {7, 8, 9}, {10, 11, 12}};<br>\r\n', '2036, 2036, 2036', '2012, 4, 2204', '2036, 10, 10', '2012, 4, 6', 'a'),
(87, '#include<stdio.h> <br>\r\nint main() <br>\r\n{ <br>\r\n  char *s[] = { \"knowledge\",\"is\",\"power\"}; <br>\r\n  char **p; <br>\r\n  p = s; <br>\r\n  printf(\"%s \", ++*p); <br>\r\n  printf(\"%s \", *p++); <br>\r\n  printf(\"%s \", ++*p); <br>\r\n  \r\n  return 0; <br>\r\n}<br>', 'is power', 'nowledge nowledge s', 'is ower', 'nowledge knowledge is', 'b'),
(88, '#include <stdio.h><br>\r\nint main()<br>\r\n{<br>\r\n    int i = 5, j = 10, k = 15;<br>\r\n    printf(\"%d \", sizeof(k /= i + j));<br>\r\n    printf(\"%d\", k);<br>\r\n    return 0;<br>\r\n}<br>\r\nAssume size of an integer as 4 bytes. What is the output of above program?', '4 1', '4 15', '2 1', 'compile time error', 'b'),
(89, 'Consider the following variable declarations and definitions in C<br>\r\ni) int var_9 = 1;<br>\r\nii) int9_var = 2;<br>\r\niii) int_ = 3;<br>\r\nChoose the correct statement w.r.t. above variables<br>\r\n', 'Both (i) and (iii) are valid.', 'Only (i) is valid', 'Both (i) and (ii)  are valid.', 'All are valid.', 'a'),
(90, 'What will be output if you will compile and execute the following c code?<br>\r\n\r\nvoid start();<br>\r\nvoid end();<br>\r\n#pragma startup start<br>\r\n#pragma exit end<br>\r\nint static i;<br>\r\nvoid main(){<br>\r\nprintf(\"\r\nmain function: %d\",++i);<br>\r\n}<br>\r\nvoid start(){<br>\r\nclrscr();<br>\r\nprintf(\"\r\nstar', 'main function: 2\r\n  start function: 1\r\n  end function:3\r\n', 'start function: 1\r\n   main function: 2\r\n   end function:3', 'main function: 2\r\n    end function:3\r\n   start function: 1', 'Compiler error', 'b'),
(91, 'Minimum number of temporary variables needed to swap the contents of 2 variables is:<br>\r\n', '0', '1', '2', '3', 'a'),
(92, 'Let x be an integer which can take a value of 0 or 1. The statement if(x = =0) x = 1; else x = 0; is equivalent to which one of the following?<br>', 'x=1-x;', 'x=1+x;', 'x=x-1;', 'x=1%x;', 'a'),
(93, 'To accept 100 different values into the array we require<br>\r\n	', 'Loop', ' If condition', 'Function', 'Structure', 'a'),
(94, 'What will be output if you will compile and execute the following c code?<br>\r\n\r\n#include \"string.h\"<br>\r\nvoid main(){<br>\r\nclrscr();<br>\r\nprintf(\"%d%d\",sizeof(\"string\"),strlen(\"string\"));<br>\r\ngetch();<br>\r\n}<br>\r\n\r\n\r\n', ' 6 6', ' 7 7', '6 7', '7 6', 'd'),
(95, 'Find out the correct statement for the following program.<br>\r\n#include \"stdio.h\"<br>\r\n \r\nint* arrPtr[5];<br>\r\n \r\nint main()<br>\r\n{<br>\r\n if(*(arrPtr+2) == *(arrPtr+4))<br>\r\n {<br>\r\n   printf(\"Equal!\");<br>\r\n }<br>\r\n else<br>\r\n {<br>\r\n  printf(\"Not Equal\");<br>\r\n }<br>\r\n return0;<br>\r\n}\r\n<br>', 'Compile Error', 'It\'ll always print Equal.', 'It\'ll always print Not Equal', 'Since elements of arrPtr aren\'t initialized in the program ,it\'ll print either Equal oe Not Equa', 'b'),
(96, 'Which of the following is allowed in a C Arithmetic Instruction?<br>\r\n      	', '[ ]', '{ }', '( )', 'None of the above', 'c'),
(97, 'What will be output if you will compile and execute the following c code?<br>\r\nvoid main(){<br>\r\nint a,b;<br>\r\n   a=1,3,15;<br>\r\n   b=(2,4,6);<br>\r\nclrscr();<br>\r\nprintf(\"%d \",a+b);<br>\r\ngetch();<br>\r\n}<br>\r\n\r\n\r\n', '3', '21', '17', '7', 'd'),
(98, 'What is the output of the following C code(on a 64 bit machine)?<br>\r\n #include <stdio.h><br>\r\n    union Sti<br>\r\n    {<br>\r\n        int nu;<br>\r\n        char m;<br>\r\n    };<br>\r\n    int main()<br>\r\n    {<br>\r\n        union Sti s;<br>\r\n        printf(\"%d\", sizeof(s));<br>\r\n        return 0;<br>\r\n   ', '8', '5', '9', '4', 'd'),
(99, 'What will be output if you will compile and execute the following c code?<br>\r\nvoid main(){<br>\r\nint a=25;<br>\r\nclrscr();<br>\r\nprintf(\"%o %x\",a,a);<br>\r\ngetch();<br>\r\n}<br>\r\n\r\n\r\n', '25 25', '025 0x25', '12 42', '31 19', 'd'),
(100, '#include <stdio.h><br>\r\n  int main()<br>\r\n    {<br>\r\n        int x = 10000;<br>\r\n        double y = 56;<br>\r\n        int *p = &x;<br>\r\n        double *q = &y;<br>\r\n        printf(\"p and q are %d and %d\", sizeof(p), sizeof(q));<br>\r\n        return 0;<br>\r\n    }<br>\r\nThe output is:<br>\r\n\r\n', 'p and q are 4 and 4', 'p and q are 4 and 8', 'Compiler error', 'p and q are 2 and 8', 'a'),
(101, 'NULL pointer and UN initialised pointer are the same?<br>\r\n\r\n', 'true', 'false', 'depends upon the program', 'none', 'b'),
(102, 'Predict the output of the below program:<br>\r\n#include <stdio.h><br>\r\n#define EVEN 0<br>\r\n#define ODD 1<br>\r\nint main()<br>\r\n{<br>\r\n    int i = 3;<br>\r\n    switch (i & 1)<br>\r\n    {<br>\r\n        case EVEN: <br>printf(\"Even\");<br>\r\n                break;<br>\r\n        case ODD: <br>printf(\"Odd\");<br>\r\n                break;<br>\r\n        default: <br>printf(\"Default\");<br>\r\n    }<br>\r\n    return 0;<br>\r\n}<br>', 'Even', 'Odd', 'Default', 'compilation error', 'b'),
(103, 'Declaration int *(*p) int(*a)(i)  is:<br>\r\n', 'A pointer to a function that accepts an integeer argument and returns an integer', 'A pointer to a,which returns an integer', 'A pointer to p,that returns an integer', 'none', 'a'),
(104, 'Output is:\r\n#include<stdio.h><br>\r\n   #include<stdlib.h><br>\r\n\r\nint main()<br>\r\n   {<br>\r\nint *ptr;<br>\r\nptr = realloc(0,sizeof(int)*10);<br>\r\nreturn 0;<br>\r\n   }<br>\r\n\r\n\r\n', '0', '10', '40', 'none of the mentioned', 'c'),
(105, 'strcat() adds null character:<br>\r\n\r\n', ' only if there is space', 'always', 'depends upon the standard', 'depends upon the compiler', 'b'),
(106, 'Which   of   the   following   is   not   modifier   of   data   type   in   c?<br>\r\n\r\n', ' extern', 'interrupt', 'huge', 'All   of   these   are   modifiers   of   data   type  ', 'd');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ques_ans`
--
ALTER TABLE `ques_ans`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `ques_ans`
--
ALTER TABLE `ques_ans`
  MODIFY `id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=107;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
